server:
  port: 8082

spring:
  application:
    name: est-service-prod

  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8